'use strict';
const $=s=>document.querySelector(s), main=$('#main');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storage={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const state={lang:storage.get('bible.lang','s'),english:storage.get('bible.en',false),size:storage.get('bible.size',21),testament:'old'};
if(!['s','t'].includes(state.lang))state.lang='s';
state.size=Math.max(16,Math.min(32,Number(state.size)||21));
const name=b=>state.lang==='t'?b.traditional:b.name;
const url=(i,c=1,v='')=>`#read/${BIBLE[i].id}/${c}${v?'/'+v:''}`;
const groups=[['摩西五经',0,5],['历史书',5,17],['诗歌与智慧书',17,22],['大先知书',22,27],['小先知书',27,39],['四福音书',39,43],['历史书',43,44],['保罗书信',44,57],['普通书信',57,65],['启示录',65,66]];
const quotes=[['太初有道，道与神同在，道就是神。','约翰福音 1 : 1',42,1,1],['耶和华是我的牧者，我必不至缺乏。','诗篇 23 : 1',18,23,1],['你们必晓得真理，真理必叫你们得以自由。','约翰福音 8 : 32',42,8,32],['使人和睦的人有福了！因为他们必称为神的儿子。','马太福音 5 : 9',39,5,9]];
let quoteIndex=0,toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',2200)}
function settings(){document.documentElement.style.setProperty('--verse-size',state.size+'px');document.querySelectorAll('[data-lang]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.lang===state.lang));$('#english').setAttribute('aria-pressed',state.english)}
function catalog(){const start=state.testament==='old'?0:39,end=state.testament==='old'?39:66;return groups.filter(g=>g[1]>=start&&g[1]<end).map(g=>`<div class="book-group"><div class="group-label">${g[0]}</div><div class="book-grid">${BIBLE.slice(g[1],g[2]).map((b,j)=>`<a class="book-link" href="${url(g[1]+j)}"><span>${esc(name(b))}</span><small>${b.s.length}</small></a>`).join('')}</div></div>`).join('')}
function hero(){const q=quotes[quoteIndex];return `<span class="eyebrow">静 心 · 读 经</span><blockquote>${q[0]}</blockquote><div class="hero-bottom"><a href="${url(q[2],q[3],q[4])}">${q[1]} ↗</a><div class="dots">${quotes.map((_,i)=>`<button class="${i===quoteIndex?'active':''}" data-quote="${i}" aria-label="第 ${i+1} 条经文"></button>`).join('')}</div></div>`}
function home(){const recent=storage.get('bible.recent',null);main.innerHTML=`<div class="hero-layout"><section class="hero" aria-label="精选经文">${hero()}</section><section class="search-panel"><p class="section-kicker">READ & REFLECT</p><h2>从一句经文开始</h2><form id="search-form"><label for="keyword">在此输入关键词搜索全本圣经</label><div class="input-row"><input id="keyword" name="q" placeholder="例如：信心、盼望、爱" required maxlength="100"><button class="primary">搜索</button></div></form><form id="read-form" class="quick-read"><label for="book-select">或者直接选择经文阅读</label><div class="input-row"><select id="book-select" aria-label="选择经卷">${BIBLE.map((b,i)=>`${i===0?'<optgroup label="旧约">':i===39?'</optgroup><optgroup label="新约">':''}<option value="${i}">${esc(name(b))}</option>`).join('')}</optgroup></select><select id="chapter-select" aria-label="选择章节"></select><button class="primary">阅读</button></div></form><p class="hint">66 卷 · 1,189 章 · 和合本</p>${recent&&BIBLE[recent.i]?`<a class="resume" href="${url(recent.i,recent.c)}">继续上次阅读：${esc(name(BIBLE[recent.i]))} ${recent.c} 章 →</a>`:''}</section></div><section class="catalog"><div class="section-head"><h2>圣经目录 <small>　选择一卷，开始阅读</small></h2><div class="testaments"><button data-testament="old" aria-pressed="${state.testament==='old'}">旧约 39</button><button data-testament="new" aria-pressed="${state.testament==='new'}">新约 27</button></div></div><div id="catalog-books">${catalog()}</div></section><div class="quiet-note">留一段安静的时间，与经文相遇</div>`;fillChapters();$('#book-select').onchange=fillChapters;$('#read-form').onsubmit=e=>{e.preventDefault();location.hash=url(Number($('#book-select').value),Number($('#chapter-select').value))};$('#search-form').onsubmit=e=>{e.preventDefault();startSearch($('#keyword').value)}}
function fillChapters(){const i=Number($('#book-select').value);$('#chapter-select').innerHTML=BIBLE[i].s.map((_,n)=>`<option value="${n+1}">${n+1} 章</option>`).join('')}
function startSearch(q,scope='all'){q=q.trim();if(q)location.hash=`#search/${encodeURIComponent(q)}/${scope}/1`;else toast('请输入搜索关键词')}
function read(id,chapter,verse){const i=BIBLE.findIndex(b=>b.id===id),c=Number(chapter);if(i<0||!Number.isInteger(c)||c<1||c>BIBLE[i].s.length)return missing();const b=BIBLE[i],vs=b[state.lang][c-1];storage.set('bible.recent',{i,c});const saved=storage.get('bible.bookmarks',[]).some(x=>x.i===i&&x.c===c);let prev=c>1?url(i,c-1):i>0?url(i-1,BIBLE[i-1].s.length):null,next=c<b.s.length?url(i,c+1):i<65?url(i+1,1):null;document.title=`${name(b)} ${c} 章 · 中文和合本圣经`;
main.innerHTML=`<div class="breadcrumb"><a href="#home">圣经目录</a> / ${i<39?'旧约':'新约'} / ${esc(name(b))}</div><div class="reader-head"><h1>${esc(name(b))} <span>${c}</span> 章</h1><div class="reader-actions"><button class="outline" id="save">${saved?'★ 已加书签':'☆ 加入书签'}</button><button class="outline" id="copy">复制本章</button><a class="outline" href="#saved">我的书签</a></div></div><nav class="chapter-list" aria-label="章节">${b.s.map((_,j)=>`<a href="${url(i,j+1)}" ${j+1===c?'aria-current="page"':''}>${j+1}</a>`).join('')}</nav><div class="reading">${[...new Set([...Object.keys(vs),...(state.english?Object.keys(b.en[c-1]):[])])].map(Number).sort((a,b)=>a-b).map(n=>`<div class="verse" id="verse-${n}"><a class="verse-number" href="${url(i,c,n)}" aria-label="第 ${n} 节">${n}</a><div><div class="verse-text">${esc(vs[n]||'〔本译本无此节号〕')}</div>${state.english?`<div class="en" lang="en">${esc(b.en[c-1][n]||'[No verse under this number in this edition.]')}</div>`:''}</div></div>`).join('')}</div><div class="pager">${prev?`<a class="outline" href="${prev}">← 上一章</a>`:'<span>全书起始</span>'}<a href="#home">目录</a>${next?`<a class="outline" href="${next}">下一章 →</a>`:'<span>全书结束</span>'}</div>${state.english?'<p class="hint" style="text-align:center">中英按原数据节号并排显示；个别章节的分节方式不同。</p>':''}`;
$('#save').onclick=()=>{let all=storage.get('bible.bookmarks',[]);const found=all.some(x=>x.i===i&&x.c===c);all=all.filter(x=>!(x.i===i&&x.c===c));if(!found)all.push({i,c});storage.set('bible.bookmarks',all);$('#save').textContent=found?'☆ 加入书签':'★ 已加书签';toast(found?'已移除书签':'已保存到我的书签')};$('#copy').onclick=async()=>{const text=`${name(b)} 第 ${c} 章\n`+Object.entries(vs).map(([n,t])=>`${n} ${t}${state.english?'\n'+(b.en[c-1][n]||''):''}`).join('\n');try{await navigator.clipboard.writeText(text);toast('已复制本章经文')}catch{download(text,`${name(b)}-${c}.txt`);toast('已改为下载本章文本')}};if(verse)requestAnimationFrame(()=>{const v=document.getElementById('verse-'+Number(verse));if(v){v.style.background='#f3edd7';v.scrollIntoView({block:'center'})}})}
function highlight(text,q){const parts=String(text).split(new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','gi'));return parts.map((p,i)=>i%2?'<mark>'+esc(p)+'</mark>':esc(p)).join('')}
function search(q,scope='all',page=1){if(!q||q.length>100)return missing();const results=[],needle=q.toLowerCase();BIBLE.forEach((b,i)=>{if(scope==='old'&&i>=39||scope==='new'&&i<39)return;b[state.lang].forEach((ch,j)=>Object.entries(ch).forEach(([n,text])=>{if(text.toLowerCase().includes(needle)||b[state.lang==='s'?'t':'s'][j][n]?.toLowerCase().includes(needle)||b.en[j][n]?.toLowerCase().includes(needle))results.push({i,c:j+1,n,text})}))});const pages=Math.max(1,Math.ceil(results.length/30));page=Math.min(pages,Math.max(1,Number(page)||1));main.innerHTML=`<div class="breadcrumb"><a href="#home">圣经目录</a> / 搜索</div><h1>查找经文</h1><form id="results-form" class="search-controls"><input id="search-query" aria-label="搜索关键词" value="${esc(q)}" required maxlength="100"><select id="scope" aria-label="搜索范围"><option value="all">全本圣经</option><option value="old">仅旧约</option><option value="new">仅新约</option></select><button class="primary">搜索</button></form><p class="hint">“${esc(q)}” · 找到 ${results.length} 节经文 · 第 ${page} / ${pages} 页</p>${results.slice((page-1)*30,page*30).map(r=>`<a class="result" href="${url(r.i,r.c,r.n)}"><strong>${esc(name(BIBLE[r.i]))} ${r.c} : ${r.n} →</strong><p>${highlight(r.text,q)}</p>${state.english||/[a-z]/i.test(q)?`<div class="en">${highlight(BIBLE[r.i].en[r.c-1][r.n]||'',q)}</div>`:''}</a>`).join('')||'<div class="empty">没有找到匹配经文。请试试更短的关键词。</div>'}<div class="pager">${page>1?`<a class="outline" href="#search/${encodeURIComponent(q)}/${scope}/${page-1}">← 上一页</a>`:''}${page<pages?`<a class="outline" href="#search/${encodeURIComponent(q)}/${scope}/${page+1}">下一页 →</a>`:''}</div>`;$('#scope').value=scope;$('#results-form').onsubmit=e=>{e.preventDefault();startSearch($('#search-query').value,$('#scope').value)}}
function news(){
  document.title='圣经动态 · 中文和合本圣经';
  main.innerHTML=`<div class="prose news-page">
    <div class="breadcrumb"><a href="#home">圣经目录</a> / 圣经动态</div>
    <h1>圣经动态</h1>
    <article class="news-entry" aria-labelledby="news-wedevote-lsb">
      <h2 id="news-wedevote-lsb">微读圣经上线 LSB 译本</h2>
      <div class="news-meta"><span>来源：<a href="https://www.facebook.com/wedevotebible" target="_blank" rel="noopener">WeDevote Bible 微读圣经</a></span><span>收录：<time datetime="2026-09-23">2026-09-23</time></span><a href="https://www.facebook.com/wedevotebible/posts/pfbid0CcuLwnbSuhLUXVUoeSXTNheaYjvnbjKL2XYoUazrZG3BRji9G2L51ac4QeVcG3Vul" target="_blank" rel="noopener">查看原帖 ↗</a></div>
      <div class="news-body" lang="zh-Hant">
        <p>和合本把神的名譯作「耶和華」——那是希伯來文四個字母 YHWH 的音譯。但你對照英文聖經會發現，KJV、NIV、ESV 大多譯成 the LORD（全大寫）：名字變成了頭銜。</p>
        <p>LSB（Legacy Standard Bible，The Lockman Foundation 2021）做了和和合本一樣的選擇。官網的說法是：「In the LSB, God's covenant name is rendered as Yahweh, as opposed to LORD.」短形式還保留了 Yah。</p>
        <p>它不是從零開始的新譯本，是在 NASB 95 上修訂的：「The goal was not to create a new translation but to refine an already excellent one.」譯經原則是 word-for-word，官網自比為「a window」——讓讀者看見作者的原意，而不是譯者的觀點。</p>
        <p>LSB 現在可以在微讀聖經裏讀。</p>
        <p class="news-howto">打開「微讀聖經」App → 點首頁「閱讀聖經」→ 點頁面上方的聖經版本 → 下滑即可看到 LSB</p>
        <p>網頁版：<a href="https://wedevote.com/bible/lsb/gen/1" target="_blank" rel="noopener">wedevote.com/bible/lsb/gen/1 ↗</a></p>
      </div>
      <figure class="news-figure"><a href="assets/news/wedevote-lsb.jpg" target="_blank" rel="noopener" aria-label="查看微读圣经 LSB 上线配图原图"><img src="assets/news/wedevote-lsb.jpg" width="1638" height="2048" alt="微读圣经宣布收录 LSB 英文译本：逐字直译、承继 NASB、将神的名译作 Yahweh，可与中文译本对照阅读。" loading="lazy" decoding="async"></a><figcaption>微读圣经 LSB 译本上线配图 · 点击查看原图</figcaption></figure>
    </article>
  </div>`;
}
function bookmarks(){const all=storage.get('bible.bookmarks',[]).filter(x=>BIBLE[x.i]?.s[x.c-1]);main.innerHTML=`<div class="breadcrumb"><a href="#home">圣经目录</a> / 我的书签</div><h1>我的书签</h1><p class="hint">书签保存在当前浏览器中。</p>${all.map(x=>`<a class="result" href="${url(x.i,x.c)}"><strong>${esc(name(BIBLE[x.i]))} ${x.c} 章 →</strong><p>${esc(BIBLE[x.i][state.lang][x.c-1][1]||'')}</p></a>`).join('')||'<div class="empty">还没有书签。阅读时点击“加入书签”，下次从这里继续。</div>'}`}
function download(text,filename){const a=document.createElement('a'),u=URL.createObjectURL(new Blob(['\ufeff',text],{type:'text/plain;charset=utf-8'}));a.href=u;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function downloads(){main.innerHTML=`<div class="prose"><div class="breadcrumb"><a href="#home">圣经目录</a> / 资源下载</div><h1>把经文留在手边</h1><p>下载 TXT 文本或 PDF，用于离线阅读。</p>${[['s','和合本 · 简体'],['t','和合本 · 繁体'],['en','King James Version']].map(([k,n])=>`<div class="download-row"><div><h3>${n}</h3><p>66 卷 · TXT 文本</p></div><button class="outline" data-download="${k}">下载全文 ↓</button></div>`).join('')}<h2 class="pdf-heading">NET 圣经中文版</h2><p>新英语译本 NET 的中文版（简体） · 译者序及 66 卷。原站更新日期：2011-12-15。</p><div class="download-row pdf-row"><div><h3>全部 67 份 PDF</h3><p>可逐卷下载，也可下载包含序言的完整 ZIP 文件包。</p></div><div class="pdf-actions"><a class="outline" href="downloads/net-chinese/">逐卷下载</a><a class="outline" href="downloads/net-chinese/sc_pdf_20111215.zip" download>整包下载 ↓</a></div></div><p>原始来源：<a href="https://bible.org/chinese/e/download/pdf" target="_blank" rel="noopener">Bible.org 中文 NET PDF 下载页</a>。版权与使用说明请参见原始来源及译者序。</p><h2 class="pdf-heading">译名定制版 PDF</h2>${[['sigao-with-cuv-names','《思高本圣经》PDF','和合本译名定制版','梅瑟→摩西'],['cuv-with-sigao-names','《和合本圣经》PDF','思高本译名定制版','摩西→梅瑟']].map(([repo,title,edition,direction])=>`<div class="download-row pdf-row"><div><h3>${title}</h3><p>${edition}：<strong>${direction}</strong></p></div><div class="pdf-actions"><a class="outline" href="https://github.com/baibanbao/${repo}/blob/main/pdf/${repo}.pdf" target="_blank" rel="noopener">查看 PDF</a><a class="outline" href="https://raw.githubusercontent.com/baibanbao/${repo}/main/pdf/${repo}.pdf" target="_blank" rel="noopener" download="${repo}.pdf">下载 PDF ↓</a></div></div>`).join('')}</div>`}
function about(){main.innerHTML=`<article class="prose"><div class="breadcrumb"><a href="#home">圣经目录</a> / 关于本站</div><h1>让阅读回到经文本身</h1><p>这是参考 <a href="https://www.chinesebibleonline.com/" target="_blank" rel="noopener">中文圣经在线</a> 制作的独立无广告版本，与原站没有运营或隶属关系。保留经卷目录、全文搜索和中英对照，并适配手机阅读。</p><h2>经文版本</h2><p>中文使用和合本简体与繁体数据，英文使用 King James Version（KJV）。数据来自 <a href="https://getbible.net/api/" target="_blank" rel="noopener">GetBible</a> 的 cus、cut、kjv 数据集，来源目录将中文数据标为 Public Domain；KJV 数据标为 GPL，CrossWire 在随附说明中允许为任何目的使用其整理文本。完整来源与许可说明保存在 data/translation-metadata.json。经文按原始节号显示；不同译本个别分节方式可能不同。NIV 未收录。</p><h2>没有广告，也没有追踪</h2><p>阅读、搜索、字体设置和书签均在本地浏览器中完成。页面不会加载广告、统计脚本或第三方字体。所有经文和首页图片随站点一同保存，无需向原站请求经文。</p><h2>页面来源</h2><p>布局、配色及首页风景图参考原站；本站标识重新绘制。原站图片的权利归其权利人所有。网站源码托管于 GitHub，页面由 GitHub Pages 提供。</p></article>`}
function missing(){main.innerHTML='<div class="empty"><h1>没有找到这一页</h1><a class="outline" href="#home">返回圣经目录</a></div>'}
function route(){if(!window.BIBLE){main.innerHTML='<div class="empty">经文数据未载入，请检查 data/bible.js 是否与网页保存在同一目录，然后刷新。</div>';return}settings();document.title='中文和合本圣经';let parts;try{parts=location.hash.slice(1).split('/').map(decodeURIComponent)}catch{return missing()}window.scrollTo(0,0);switch(parts[0]){case 'read':read(parts[1],parts[2],parts[3]);break;case 'search':search(parts[1],['all','old','new'].includes(parts[2])?parts[2]:'all',parts[3]);break;case 'news':news();break;case 'bookmarks':history.replaceState(null,'','#news');news();break;case 'saved':bookmarks();break;case 'downloads':downloads();break;case 'about':about();break;case '':case 'home':home();break;default:missing()}}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.lang){state.lang=el.dataset.lang;storage.set('bible.lang',state.lang);route()}if(el.id==='english'){state.english=!state.english;storage.set('bible.en',state.english);route()}if(['smaller','larger'].includes(el.id)){state.size=Math.max(16,Math.min(32,state.size+(el.id==='larger'?1:-1)));storage.set('bible.size',state.size);settings();toast('经文字号：'+state.size)}if(el.dataset.testament){state.testament=el.dataset.testament;$('#catalog-books').innerHTML=catalog();document.querySelectorAll('[data-testament]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.testament===state.testament))}if(el.dataset.quote!==undefined){quoteIndex=Number(el.dataset.quote);$('.hero').innerHTML=hero()}if(el.dataset.download){const k=el.dataset.download,text=BIBLE.map(b=>(k==='t'?b.traditional:b.name)+'\n\n'+b[k].map((ch,c)=>`第 ${c+1} 章\n`+Object.entries(ch).map(([n,t])=>`${c+1}:${n} ${t}`).join('\n')).join('\n\n')).join('\n\n');download(text,`bible-${k}.txt`);toast('已生成全文下载')}});
window.addEventListener('hashchange',route);route();
